/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ActivityFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activities"
      | "activityCount"
      | "activityRegistry"
      | "createDepositChallenge"
      | "getAllActivities"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DepositChallengeCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "activities",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activityCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createDepositChallenge",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllActivities",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "activities", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activityCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDepositChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllActivities",
    data: BytesLike
  ): Result;
}

export namespace DepositChallengeCreatedEvent {
  export type InputTuple = [
    challengeAddress: AddressLike,
    creator: AddressLike,
    activityId: BigNumberish,
    title: string
  ];
  export type OutputTuple = [
    challengeAddress: string,
    creator: string,
    activityId: bigint,
    title: string
  ];
  export interface OutputObject {
    challengeAddress: string;
    creator: string;
    activityId: bigint;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ActivityFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ActivityFactory;
  waitForDeployment(): Promise<this>;

  interface: ActivityFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activities: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  activityCount: TypedContractMethod<[], [bigint], "view">;

  activityRegistry: TypedContractMethod<[], [string], "view">;

  createDepositChallenge: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _depositAmount: BigNumberish,
      _totalRounds: BigNumberish,
      _maxParticipants: BigNumberish,
      _isPublic: boolean,
      _creatorName: string
    ],
    [[string, bigint] & { challengeAddress: string; activityId: bigint }],
    "nonpayable"
  >;

  getAllActivities: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activities"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "activityCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createDepositChallenge"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _depositAmount: BigNumberish,
      _totalRounds: BigNumberish,
      _maxParticipants: BigNumberish,
      _isPublic: boolean,
      _creatorName: string
    ],
    [[string, bigint] & { challengeAddress: string; activityId: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllActivities"
  ): TypedContractMethod<[], [string[]], "view">;

  getEvent(
    key: "DepositChallengeCreated"
  ): TypedContractEvent<
    DepositChallengeCreatedEvent.InputTuple,
    DepositChallengeCreatedEvent.OutputTuple,
    DepositChallengeCreatedEvent.OutputObject
  >;

  filters: {
    "DepositChallengeCreated(address,address,uint256,string)": TypedContractEvent<
      DepositChallengeCreatedEvent.InputTuple,
      DepositChallengeCreatedEvent.OutputTuple,
      DepositChallengeCreatedEvent.OutputObject
    >;
    DepositChallengeCreated: TypedContractEvent<
      DepositChallengeCreatedEvent.InputTuple,
      DepositChallengeCreatedEvent.OutputTuple,
      DepositChallengeCreatedEvent.OutputObject
    >;
  };
}
