/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ActivityRegistry {
  export type ActivityMetadataStruct = {
    activityContract: AddressLike;
    creator: AddressLike;
    creatorName: string;
    title: string;
    description: string;
    createdAt: BigNumberish;
    isPublic: boolean;
    incentiveType: BigNumberish;
  };

  export type ActivityMetadataStructOutput = [
    activityContract: string,
    creator: string,
    creatorName: string,
    title: string,
    description: string,
    createdAt: bigint,
    isPublic: boolean,
    incentiveType: bigint
  ] & {
    activityContract: string;
    creator: string;
    creatorName: string;
    title: string;
    description: string;
    createdAt: bigint;
    isPublic: boolean;
    incentiveType: bigint;
  };
}

export interface ActivityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activities"
      | "activityCount"
      | "contractToActivity"
      | "getActivityMetadata"
      | "getActivityMetadataTuple"
      | "getUserActivities"
      | "registerActivity"
      | "userActivities"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ActivityRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "activities",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activityCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contractToActivity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActivityMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActivityMetadataTuple",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserActivities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerActivity",
    values: [
      AddressLike,
      string,
      string,
      boolean,
      BigNumberish,
      AddressLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userActivities",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "activities", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activityCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractToActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActivityMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActivityMetadataTuple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserActivities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userActivities",
    data: BytesLike
  ): Result;
}

export namespace ActivityRegisteredEvent {
  export type InputTuple = [
    activityId: BigNumberish,
    creator: AddressLike,
    activityContract: AddressLike,
    title: string
  ];
  export type OutputTuple = [
    activityId: bigint,
    creator: string,
    activityContract: string,
    title: string
  ];
  export interface OutputObject {
    activityId: bigint;
    creator: string;
    activityContract: string;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ActivityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ActivityRegistry;
  waitForDeployment(): Promise<this>;

  interface: ActivityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activities: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint, boolean, bigint] & {
        activityContract: string;
        creator: string;
        creatorName: string;
        title: string;
        description: string;
        createdAt: bigint;
        isPublic: boolean;
        incentiveType: bigint;
      }
    ],
    "view"
  >;

  activityCount: TypedContractMethod<[], [bigint], "view">;

  contractToActivity: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  getActivityMetadata: TypedContractMethod<
    [_activityId: BigNumberish],
    [ActivityRegistry.ActivityMetadataStructOutput],
    "view"
  >;

  getActivityMetadataTuple: TypedContractMethod<
    [_activityId: BigNumberish],
    [
      [string, string, string, string, string, bigint, boolean, bigint] & {
        activityContract: string;
        creator: string;
        creatorName: string;
        title: string;
        description: string;
        createdAt: bigint;
        isPublic: boolean;
        incentiveType: bigint;
      }
    ],
    "view"
  >;

  getUserActivities: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  registerActivity: TypedContractMethod<
    [
      _activityContract: AddressLike,
      _title: string,
      _description: string,
      _isPublic: boolean,
      _incentiveType: BigNumberish,
      _creator: AddressLike,
      _creatorName: string
    ],
    [bigint],
    "nonpayable"
  >;

  userActivities: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activities"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint, boolean, bigint] & {
        activityContract: string;
        creator: string;
        creatorName: string;
        title: string;
        description: string;
        createdAt: bigint;
        isPublic: boolean;
        incentiveType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "activityCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "contractToActivity"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActivityMetadata"
  ): TypedContractMethod<
    [_activityId: BigNumberish],
    [ActivityRegistry.ActivityMetadataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActivityMetadataTuple"
  ): TypedContractMethod<
    [_activityId: BigNumberish],
    [
      [string, string, string, string, string, bigint, boolean, bigint] & {
        activityContract: string;
        creator: string;
        creatorName: string;
        title: string;
        description: string;
        createdAt: bigint;
        isPublic: boolean;
        incentiveType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserActivities"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "registerActivity"
  ): TypedContractMethod<
    [
      _activityContract: AddressLike,
      _title: string,
      _description: string,
      _isPublic: boolean,
      _incentiveType: BigNumberish,
      _creator: AddressLike,
      _creatorName: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userActivities"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ActivityRegistered"
  ): TypedContractEvent<
    ActivityRegisteredEvent.InputTuple,
    ActivityRegisteredEvent.OutputTuple,
    ActivityRegisteredEvent.OutputObject
  >;

  filters: {
    "ActivityRegistered(uint256,address,address,string)": TypedContractEvent<
      ActivityRegisteredEvent.InputTuple,
      ActivityRegisteredEvent.OutputTuple,
      ActivityRegisteredEvent.OutputObject
    >;
    ActivityRegistered: TypedContractEvent<
      ActivityRegisteredEvent.InputTuple,
      ActivityRegisteredEvent.OutputTuple,
      ActivityRegisteredEvent.OutputObject
    >;
  };
}
