/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ActivityFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ActivityFactory__factory>;
    getContractFactory(
      name: "ActivityRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ActivityRegistry__factory>;
    getContractFactory(
      name: "Challenge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Challenge__factory>;
    getContractFactory(
      name: "NFTActivity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NFTActivity__factory>;
    getContractFactory(
      name: "NFTActivityFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NFTActivityFactory__factory>;

    getContractAt(
      name: "ActivityFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ActivityFactory>;
    getContractAt(
      name: "ActivityRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ActivityRegistry>;
    getContractAt(
      name: "Challenge",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Challenge>;
    getContractAt(
      name: "NFTActivity",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NFTActivity>;
    getContractAt(
      name: "NFTActivityFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NFTActivityFactory>;

    deployContract(
      name: "ActivityFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ActivityFactory>;
    deployContract(
      name: "ActivityRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ActivityRegistry>;
    deployContract(
      name: "Challenge",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Challenge>;
    deployContract(
      name: "NFTActivity",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NFTActivity>;
    deployContract(
      name: "NFTActivityFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NFTActivityFactory>;

    deployContract(
      name: "ActivityFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ActivityFactory>;
    deployContract(
      name: "ActivityRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ActivityRegistry>;
    deployContract(
      name: "Challenge",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Challenge>;
    deployContract(
      name: "NFTActivity",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NFTActivity>;
    deployContract(
      name: "NFTActivityFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NFTActivityFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
