/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface NFTActivityFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activityRegistry"
      | "createNFTActivity"
      | "getAllNFTActivities"
      | "nftActivities"
      | "nftActivityCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NFTActivityCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "activityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createNFTActivity",
    values: [string, string, BigNumberish, BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllNFTActivities",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftActivities",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nftActivityCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "activityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNFTActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllNFTActivities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftActivities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftActivityCount",
    data: BytesLike
  ): Result;
}

export namespace NFTActivityCreatedEvent {
  export type InputTuple = [
    activityAddress: AddressLike,
    creator: AddressLike,
    activityId: BigNumberish,
    title: string
  ];
  export type OutputTuple = [
    activityAddress: string,
    creator: string,
    activityId: bigint,
    title: string
  ];
  export interface OutputObject {
    activityAddress: string;
    creator: string;
    activityId: bigint;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NFTActivityFactory extends BaseContract {
  connect(runner?: ContractRunner | null): NFTActivityFactory;
  waitForDeployment(): Promise<this>;

  interface: NFTActivityFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activityRegistry: TypedContractMethod<[], [string], "view">;

  createNFTActivity: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _totalRounds: BigNumberish,
      _maxParticipants: BigNumberish,
      _isPublic: boolean,
      _creatorName: string
    ],
    [[string, bigint] & { activityAddress: string; activityId: bigint }],
    "nonpayable"
  >;

  getAllNFTActivities: TypedContractMethod<[], [string[]], "view">;

  nftActivities: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  nftActivityCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createNFTActivity"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _totalRounds: BigNumberish,
      _maxParticipants: BigNumberish,
      _isPublic: boolean,
      _creatorName: string
    ],
    [[string, bigint] & { activityAddress: string; activityId: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllNFTActivities"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "nftActivities"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "nftActivityCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "NFTActivityCreated"
  ): TypedContractEvent<
    NFTActivityCreatedEvent.InputTuple,
    NFTActivityCreatedEvent.OutputTuple,
    NFTActivityCreatedEvent.OutputObject
  >;

  filters: {
    "NFTActivityCreated(address,address,uint256,string)": TypedContractEvent<
      NFTActivityCreatedEvent.InputTuple,
      NFTActivityCreatedEvent.OutputTuple,
      NFTActivityCreatedEvent.OutputObject
    >;
    NFTActivityCreated: TypedContractEvent<
      NFTActivityCreatedEvent.InputTuple,
      NFTActivityCreatedEvent.OutputTuple,
      NFTActivityCreatedEvent.OutputObject
    >;
  };
}
